common-voice/sentence-collector

- web/src/components/pages/add.jsx
> Add note about Public Domain before submitting (fixes #7)

- shared/db.js
- shared/db/collections/sentences-meta.js
- shared/db/collections/sentences.js
- web/src/actions/index.js
- web/src/components/pages/add.jsx
- web/src/containers/add.js
Please merge https://github.com/Common-Voice/sentence-collector/pull/13 before this, as it's built on top of it.
> Add 'Source' to Sentence Meta Record (fixes #6)

- doc/how-to.md
I didn't realize there was a word limit when submitting Albanian sentences, and was wondering why they kept getting rejected.
> Update how-to.md to add word limit

- shared/validation/index.js
> feat: enable kabyle verification

- shared/validation/index.js
- shared/validation/languages/ru.js
> Add validation rules for Russian language

- scripts/exporter.js
- shared/db/collections/sentences-meta.js
see https://github.com/Common-Voice/sentence-collector/issues/245 for context
@freaktechnik r?
> Export: calculate approval on export + better deduping

- web/css/review-form.css
- web/css/root.css
- web/src/components/header-btn.jsx
- web/src/components/page.jsx
Fixed changes requested and changed the size of buttons and text box to adapt it better to small screens.
> fix: mobile ui sidebar and sentence review

- web/src/components/pages/add.jsx
I took a stab at https://github.com/Common-Voice/sentence-collector/issues/102 . I ran into an edge case during manual verification where if all of the sentences are filtered out, the UI and navigation flow are a little annoying. I think that's a separate issue though. This history block would start when the Submit button is clicked, and end when all the confirmation is done and state is reset. I think it would make sense to make the block start sooner, when the sentences-input has a value, but the code would be more complicated. What do you think?
> feat: use history block to warn of unconfirmed sentences

- shared/db.js
- shared/db/collections/user.js
- web/src/actions/index.js
- web/src/components/pages/profile.jsx
- web/src/components/pages/review.jsx
- web/src/components/review-form.jsx
- web/src/containers/profile.js
- web/src/containers/review.js
- web/src/reducers/index.js
This adds the setting to enable the "Swiping Review" that @Adrijaned implemented in https://github.com/Common-Voice/sentence-collector/pull/264.
@freaktechnik if you want to review :)
@Adrijaned: if you want to test to make sure it works as desired
> feat: add Swipe Review setting

- web/src/actions/index.js
- web/src/reducers/index.js
Fixed issue #123,
Assigned to me by @MichaelKohler,
Now once the user has entered his sentence, it automatically adds it to his profile
> fix(issue #123): adding sentences adds it to profile

- web/src/components/header.jsx
https://discourse.mozilla.org/t/central-place-to-report-copyright-issues/52686
> Link to thread for copyright violations

- shared/validation/index.js
- shared/validation/languages/th.js
Propose code for Thai language validator.
See discussion in #318.
This will close #318.
> Add validator for Thai (th)

- shared/cleanup/CLEANUP.md
- shared/cleanup/index.js
- shared/cleanup/languages/th.js
- test/shared/cleanup/languages/th.js
Cleanup code for Thai and its test set.
This will resolves #324.
> Add cleanup for Thai

- .github/workflows/docker.yaml
This is the first step for enabling a full automated CI/Cd pipeline
> Add Job to build and push Docker images

- .github/workflows/export.yaml
Tested on my own repo, however I'll keep an eye out for issues.
> chore: add scheduled sentences export into Common Voice

- server/migrations/20201111000000-remove-hi-ja-sentences.js
Hopefuly it's alright, haven't done any SQL outside wikidata ever before :)
> fix: add migration to remove hi, ja copyrighted sentences

- server/lib/languages.js
add Cantonese (yue), fix https://github.com/common-voice/sentence-collector/issues/396
> add Cantonese

- README.md
Add language validation/cleanup links to "Get Involved" section in README
> Link to VALIDATION.md and CLEANUP.md

- server/lib/validation/languages/th.js
- Add new rule (no repeat: 5 consonants in a row, invalid sequence Sara A) to `STRUCTURE_REGEX`
- Add comment to each part of regex
- Remove unnecessary regexes (already covered by others)
> [th] Add few rules to STRUCTURE_REGEX + reformat

- server/lib/validation/languages/uz.js
We have basic validation rules here. More sophisticated rules will be introduced later after linguist experts' input
> validation rules for Uzbek language

- server/lib/languages.js
https://github.com/common-voice/common-voice/issues/3194
> add nan-TW (Taiwanese) language

- web/src/components/how-to.tsx
update to how to include how to reference and cc0 waiver process
> Referencing + CC0 waiver process

- web/css/footer.css
- web/css/header.css
- web/css/root.css
- web/index.html
I played around with fonts a bit, and made some adjustments. This is inspired by the CV website, but also has parts of personal test in it.
> Slight font adjustments

- web/src/components/__snapshots__/how-to.test.tsx.snap
- web/src/components/__snapshots__/review-criteria.test.tsx.snap
- web/src/components/add-language-section.test.tsx
- web/src/components/add.test.tsx
- web/src/components/my-sentences-list.test.tsx
- web/src/components/review.test.tsx
- web/src/components/submit-form.test.tsx
- web/tests/setup.ts
To unblock the pipeline until #496 is done, I added a mock for `useLocalization` to the tests.
> Mock more test strings

- web/src/components/review-form.tsx
This is a fix for https://github.com/common-voice/sentence-collector/issues/487
This had been removed from localization PR.
> Fix for uppercase keys not working #487

- web/locales/en/sentence-collector.ftl
- web/src/components/__snapshots__/review-criteria.test.tsx.snap
- web/src/components/add-language-section.tsx
- web/src/components/confirm-form.tsx
- web/src/components/footer.tsx
- web/src/components/header.tsx
- web/src/components/home.tsx
- web/src/components/how-to.tsx
- web/src/components/language-info.tsx
- web/src/components/login-button.tsx
- web/src/components/login.tsx
- web/src/components/my-sentences-list.test.tsx
- web/src/components/my-sentences-list.tsx
- web/src/components/personal-language-info.tsx
- web/src/components/profile.tsx
- web/src/components/rejected-sentences-list.test.tsx
- web/src/components/rejected-sentences-list.tsx
- web/src/components/review-criteria.tsx
- web/src/components/review-form.tsx
- web/src/components/review-link.tsx
- web/src/components/review.tsx
- web/src/components/settings.tsx
- web/src/components/stats.tsx
- web/src/components/submit-form.tsx
- web/src/urls.test.ts
This PR handles https://github.com/common-voice/sentence-collector/issues/518
+ Some minor changes in en/sentence-collector.ftl
> Localization: Removed placeholder strings in issue #518

- server/lib/validation/index.js
- server/lib/validation/languages/ig.js
@MichaelKohler  sorry i am doing it late. Here it is for Igbo.
> adding js rules for Igbo

- web/locales/en/messages.ftl
- web/src/components/__snapshots__/home.test.tsx.snap
- web/src/components/__snapshots__/how-to.test.tsx.snap
- web/src/components/__snapshots__/review-criteria.test.tsx.snap
This fixes #543 by simply eliminating extra lines in the ftl file.
> Localization: Fix for Pontoon related issue #543

- server/lib/validation/index.js
- server/lib/validation/languages/ckb.js
This adds the `ckb` validation file as discussed in #568. This still needs to be translated.
> fix: add CKB validation file

- server/lib/validation/languages/uz.js
- server/migrations/202112091162000-remove-uz-sentences-letters.js
As per https://discourse.mozilla.org/t/sentence-collector-need-help-to-remove/88934/11
> fix: add more letters to UZ validation

- server/migrations/20220220135100-remove-tok-sentences.js
https://discourse.mozilla.org/t/sentence-collector-copyright-issues/52767/51
> fix: remove certain sentences for tok language

- server/lib/validation/languages/yue.js
Changes include:
1. More comments on the rules
2. Add restrictions of no Mandarin characters
> Improve the sentence validator for yue

- README.md
- server/lib/validation/VALIDATION.md
- server/lib/validation/index.js
- server/tests/lib/validation/index.test.js
This adds NFC normalization capability for specific languages.
> feat: add normalization for specific languages

- server/migrations/20221027223900-remove-oc.js
> fix: remove all oc sentences
