web/src/components/pages/add.jsx
This should fix this issue.
I havn't tested it.
Also, it's strange that other lines in that paragraph add whitespaces automatically. Maybe this is a general issue with the templating system. Feel free to suggest a better solution.
=> Add missing whitespaces

shared/db.js, shared/languages.js
DO NOT MERGE until we have added this on the database as well.
The following needs to be done on Kinto:
```
DELETE /v1/buckets/App/collections/Sentences_Meta_zh
PUT /v1/buckets/App/collections/Sentences_Meta_zh-CN
PUT /v1/buckets/App/collections/Sentences_Meta_zh-TW
PUT /v1/buckets/App/collections/Sentences_Meta_zh-HK
```
Then everyone who has already added "Chinese" as their language to the profile will see 'UNKNOWN' and can remove Chinese and add the specific variant.
The following are additional languages we will need to create collections for:
```
PUT /v1/buckets/App/collections/Sentences_Meta_ace
PUT /v1/buckets/App/collections/Sentences_Meta_ady
PUT /v1/buckets/App/collections/Sentences_Meta_ast
PUT /v1/buckets/App/collections/Sentences_Meta_bxr
PUT …
```
=> Add different Chinese variants + more languages

web/css/root.css, web/css/spinner-button.css, web/src/components/confirm-form.jsx, web/src/components/review-form.jsx, web/src/components/spinner-button.jsx, web/src/components/submit-form.jsx
This solves issue #95. 
I created a separate and reusable component for the CSS spinner button, separate CSS from root in a different file and imported the component in each view to use it.
The changed views are:
* submit_form.jsx: Add (sidebar) -> initial form there
* confirm_form.jsx: Add (sidebar) -> view after initial submission ("confirm")
* review_form.jsx: Review (sidebar) -> this form when submitting
=> feature: Add spinner to validating/uploading hints (solves issue #95)

shared/validation/index.js, shared/validation/languages/it.js
We added a validator for the italian language matching the [Mozilla Italia guidelines](https://github.com/Sav22999/Guide/blob/master/Mozilla%20Italia/Common%20Voice/Linee%20guida%20revisione%20Common%20Voice.md) according to which sentences for the italian dataset of Common Voice have been selected up to now. 
Compared to the previous pull request this one has some little fixes in order to be successfully built by Travis.
=> Adding italian validator (with fixes)

shared/validation/index.js, shared/validation/languages/en.js, shared/validation/languages/it.js
Currently, when creating a validator for a new language, the check on sentence length can only be customized by changing the number of words it counts in a sentence. However, there are languages like Chinese or Japanese where there's often no white spaces between words. At the moment it is impossible for users of those languages to create their own validation without changing the general one. 
Furthermore, the Italian Mozilla community has until now used "at most 125 characters" as a criterion for validating sentences, and such a rule can't be enforced cleanly as of now by only editing the Italian validator. It is very important that we are able to provide sentences coherent in length to those already in the data set as neural network models like DeepSpeech benefit a lot from uniformly …
=> Give more freedom in validating sentence length

shared/validation/index.js, shared/validation/languages/en.js, shared/validation/languages/it.js
As discussed in #202, I've added a check for those characters in the middle of a sentence as they mean it's two sentences. In the Italian version we already handled `.` in the middle so it now checks for `[?!.]`.
=> Checking whether the sentence contains [?!] in the middle

shared/db/collections/sentences-meta.js
A record needs at least two "valid votes" to get into the approved state. If a record was reviewed by at least 3 persons and and there are not at least two valid votes, the record is marked as invalid.
This refactoring does not change this logic, but allows records to be moved to the approved state already after two reviews (if both approve the record).
This optimizes the review-time, as the third reviewer would have no effect.
Fixes #224
=> Update record approval logic

doc/how-to.md
This is very misleading links, especially with talking about how good subtitles for dataset is and then mentioning *open*subtitles, which are actually copyrighted. This sources contains mostly copyrighted content and do not provide an easy way to filter for PD content. Contributors interpret this links as a call to action and spend time to contribute sentences which we can't use. It already happened [with Swedish](https://discourse.mozilla.org/t/discussion-of-new-guidelines-for-uploaded-sentence-validation/37718/11), [Czech](https://github.com/Common-Voice/sentence-collector/issues/211#issuecomment-491522940) and now Russian.
=> Remove mentions of Opensubtitles.org and Common Crawl from how-to

shared/validation/languages/kab.js
a lot of particles and prepositions, pronouns in Kabyle language contain 1 or 2 letters
=> feat: add Kabyle verification

web/src/actions/index.js
ESLint was upgraded directly in master but broke the builds since it added some additional requirements.   This fixes that requirement.
Commit that broke it:
https://github.com/Common-Voice/sentence-collector/commit/c214e89a602833382b6d71b88d9ed4f37f41b8d0
This catch was just re-throwing the error so it wasn't needed
=> fix: remove try/catch that eslint(commit c214e89a) causes to break build

.babelrc, .eslintrc.json, package-lock.json, package.json, web/src/components/pages/__snapshots__/login.test.js.snap, web/src/components/pages/login.test.js, web/src/tests/testSetup.js, web/src/tests/testUtils.js
https://github.com/Common-Voice/sentence-collector/issues/90
Tried to include a few cool features of this build setup:
1. Mock Redux store
2. Jest Snapshots
3. Enzyme locating and asserting
Updated babel dependencies because I was running into compatibility errors getting Jest to run. Can expand test cases and util helpers as I get to know the code and application better.
Includes the build fix https://github.com/Common-Voice/sentence-collector/pull/243
=> build: add js tests with jest and enzyme

scripts/db-helper.js, shared/db.js, shared/db/collections/sentences-meta.js
This is a (hopefully) one-off script to correct approvals, if they have not run through the client and therefore were not correctly approved.
see #245 for context
@freaktechnik r?
=> chore: add correct approval script

scripts/db-helper.js
Something with the Nginx Proxy makes the `next` function for pagination not behave as it should. Using the IP works perfectly fine. As I don't have access to the nginx configuration or the server itself, and I don't think we'll get engineering time from people who do have access, let's just use the IP for now.
=> chore: use IP for helper scripts

.eslintrc.json, scripts/exporter.js
Thanks to @freaktechnik for this idea on how to improve the performance.
Before:
```
Starting export for de..
- Found 17700 approved sentences
- Found 17700 valid sentences
- Writing all meta data to ../voice-web/server/data/de/sentence-collector.json..
- Cleaning up sentences
- Getting CV sentences for de..
- Got 1396914 CV sentences..
- Got 9 duplicated sentences in Sentence Collector..
CHECK_CV_DUPES: 104398.344ms
- Got 17645 sentences not already existing in CV..
- Writing all sentences to ../voice-web/server/data/de/sentence-collector.txt..
```
After:
```
Starting export for de..
- Found 17700 approved sentences
- Found 17700 valid sentences
- Writing all meta data to ../voice-web/server/data/de/sentence-collector.json..
- Cleaning up sentences
- Getting CV sentences for de..
- Got …
```
=> chore: improve export performance (fixes #253)

package-lock.json, package.json, web/css/review-form.css, web/src/components/review-form.jsx, web/src/components/swipecard/CardSwitcher.jsx, web/src/components/swipecard/Cards.jsx, web/src/components/swipecard/DraggableCard.jsx, web/src/components/swipecard/NOTE, web/src/components/swipecard/SimpleCard.jsx, web/src/components/swipecard/utils.jsx
Adds a review UI mode for mobiles based on the concept of swipecards.
Basically uses https://github.com/alexandre-garrec/react-swipe-card, except its sources are directly included and somewhat edited, as I was not capable of getting it to run as is. I acknowledge that that is not an ideal solution, but consider it just a POC.
Whether the new or old UI is displayed is determined by a switch curretnly hardcoded, with no option to set from UI.
As of now, this just submits after every five sentences reviewed. That is completely fine, ecept it just fetches all the up to 10000 just after that again, and that is not good. Either add a separate submit button, or fetch only five sentences at time - though that would break the sentence sorting ATM.
This was not actually tested on mobile device due …
=> feat: mobile swipecards based UI

shared/languages.js
Hello,
Sicilian (ISO 639-2 scn) has recently entered the Common Voice family. It's present in https://raw.githubusercontent.com/mozilla/voice-web/master/locales/all.json , but not in the sentence-collector webapp.
This commit should fix it -- thank you for considering it!
=> Add Sicilian (ISO 639-2 scn)

shared/validation/index.js, shared/validation/languages/od.js
Changes are done for Odia language sentences validation are:  
1. Maximum words for validation have been increased from `14` to `30`. This is to get a meaningful sentence Odia language needs more words. Visit the [Discourse](https://discourse.mozilla.org/t/increase-the-number-of-words-limit-for-odia/41713) discussion topic for details.
2. Odia digits have been added to the digits detector RegEx.
=> Few rules of validation, have been changed for Odia language.

server/lib/validation/languages/th.js
Previously allow short word with 1-3 Latin characters, now disallow it all since it's clear that it's not desirable in the speech collection for Thai language.
=> th validator: Disallow all Latin characters

server/lib/validation/languages/th.js
We experience a difficult to read issue for long sentence.
Adjusting the length to accommodate easier reading
- Max chars: 110 -> 80
- Max running chars without a space: 80 -> 55
(These numbers are the same as in Sentence Collector: https://github.com/common-voice/cv-sentence-extractor/pull/137 )
=> Adjusting max chars of Thai sentence

server/lib/cleanup/languages/th.js, server/lib/validation/languages/th.js
- Validation will not allow emojis
- Cleanup will remove emojis
Since mid-April 2021, Mozilla Thailand Community started to add more sentences via the Sentence Collector web interface (I believe this is a preparation towards their localization event on 25 April).
One of the thing few of the members do is exporting their own Twitter archive and add them to Sentence Collector.
@wannaphong has noticed that some of the sentences have emojis. So we need to reject or remove these emojis.
=> Disallow emojis for Thai sentences

server/lib/cleanup/languages/th.js, server/lib/validation/languages/th.js
- Cleanup: Remove U+2063 (invisible separator) which occurs in Thai text cut & pasted from some text editors (like MS Word and iOS Notes) - to reduce duplicated texts
- Validation: `STRUCTURE_REGEX` to prevent having “” ‘’ and ` in a long running text (of 55 or more characters)
Note: in the Sentence Extractor, the plan is to remove U+2063 as well (same as U+200b and U+200c zero-width chars)
=> Remove U+2063 (invisible separator) from sentence

server/lib/validation/languages/th.js
- Remove unnecessary `+`s and `{n,}`s, to make the regex matches an exact number of chars (theoretically faster)
- `/[0-9]/` will do the same job as `/[0-9]+/`, for the purpose of reject any digit in the sentence
- Fix a bug in previous no consonant repeat rule (should capture the same char repeating, not just any char in the same class). My bad.
- Add few more examples to error messages
btw, impressive new error message system - thank you.
=> [th] Fix repeating chars rule + Remove unnecessary qualifiers

server/lib/cleanup/languages/th.js
Replace invalid char with a space instead of just remove it, to prevent two separated words to stick together after the removal.
Before:
- `ยิ้ม😊กิน` -> `ยิ้มกิน`
After:
- `ยิ้ม😊กิน` -> `ยิ้ม กิน`
If excessive spaces occur, they will be eliminated later.
=> [th] Prevent 2 separated words to stick together

server/lib/validation/languages/eo.js
This is a basic rule file for Esperanto based on the english rule file. The only thing I changed is that I added more forbidden letters. Most important are the letters W Q X and Y that are not part of the Esperanto alphabet. But I also added many other letters that were often a problem during the Wiki Extraction.
=> Basic rule file for Esperanto

README.md
Had to make this change when testing locally
=> chore: fix wrong auth0 callback url in README

web/css/root.css
A minor issue, but when reviewing sentences the TinderCard animation will make the horizontal (and sometimes the vertical scrollbar) appear. This is quite jarring to me.
The TinderCard library recommend using `overflow: hidden` outright, but we need to allow vertical scrolling. I couldn't find a relatively simple solution for the vertical scrollbar.
But testing most pages I could not find any which need horizontal scrolling - so using `overflow-x: hidden` should be ok atm. Though it feels a bit dirty to apply the rule to *all* pages - but making it only apply to the review page isn't straight forward (applying it to the form-div doesn't work due to the padding)
Personally I would prefer no animation on desktop, but that's another matter. (and easily solvable using a user-stylesheet) …
=> fix: prevent horizontal scrollbar from flickering during swipe

web/src/app.tsx
We should not use locale prefixed URLs for login and logout. The redirect will be to EN anyway, and we do not have any localizeable content in the success cases anyway, those are just redirects.
For the failed login case, we don't need a param, as we can negotiate the language appropriately when loading the component. Additionally I wrapped the Login Failure component into the PageContainer, so we don't lose the menu. This was a bug I recently introduced.
=> fix: do not use locale prefixed URLs for login/logout

web/locales/en/sentence-collector.ftl, web/src/l10n.tsx
As the base path for staging and production is different from local development, we need to fetch relative to the URL instead of `/locale`.
=> chore: fix locale fetching in docker container as base path is different

web/src/components/language-info.tsx
Until now we have not shown the "Add more sentences" link in the stats, except if there were absolutely no sentences in the review queue anymore. But if a user had already reviewed all of it, we didn't show the link. This changes it to always show the link when there is a nothing to review for the user, no matter if all sentences are completely reviewed or not.
=> fix: show 'Add more sentences' link in stats when no more to review for user

.github/workflows/export.yaml, scripts/export-source-strings.js
This will export the EN source FTL file to CV on every automatic export. These strings then get translated in the CV Pontoon infrastructure. This makes sure we don't need an additional project on Pontoon and can handle everything within the Common Voice project.
Do not merge this until the PR on the Common Voice side has been merged.
=> chore: adjust export to also export Sentence Collector FTL source file to CV (fixes #525)

scripts/export-source-strings.js, web/locales/en/messages.ftl
This groups the strings a bit better and adds group titles to them. This way Pontoon will show these correctly, and not taking the overarching group from CV. Additionally to that this gets rid of the comment on `sc-header-home` as it took the overall section title in the CV FTL file as a comment for that string. By adding a group title it won't happen anymore.
And lastly, this adds a localization note for the keyboard shortcut keys not being localizeable for now.
=> Better integration into Pontoon

server/lib/validation/index.js, server/lib/validation/languages/default.js, web/locales/en/messages.ftl, web/src/components/submit-form.tsx
This adds a default validator in case there is no language specific validator. Until now we've used English, but as we want to translate the generic messages I have created a default validator. This validator has translation keys as error message, which then gets transformed into a localized string in the frontend. For language specific validators we can still use hard coded error messages.
=> chore: use default validator and translate its error message (fixes #494)

web/css/profile.css, web/css/root.css, web/locales/en/messages.ftl, web/src/components/language-selector.tsx, web/src/components/profile/settings.test.tsx, web/src/components/profile/settings.tsx, web/src/l10n.tsx
This adds a UI language selector to the profile. It will show *all* the languages for now. We can't reliably use `translated.json` as it really does not give much information on how much of Sentence Collector is actually translated. Therefore I went with that approach. However, if a locale is not in `translated.json` we show a warning with a link to Pontoon to help out with translation.
@HarikalarKutusu FYI for you. I will also write a more detailed localization update on Pontoon once all the recent changes are in production.
=> feat: add UI language selector to profile (fixes #533)

web/src/components/header.tsx
Fix for https://github.com/common-voice/sentence-collector/issues/567
=> fix: link on logo in header reverts back UI to English

server/lib/sentences.js, server/routes/stats.js, server/routes/users.js, server/tests/lib/sentences.test.js, server/tests/routes/stats.test.js, web/locales/en/messages.ftl, web/src/actions/languages.test.ts, web/src/actions/languages.ts, web/src/actions/login.test.ts, web/src/actions/login.ts, web/src/components/language-info.test.tsx, web/src/components/language-info.tsx, web/src/components/pages/review.tsx, web/src/components/pages/stats.test.tsx, web/src/components/pages/stats.tsx, web/src/components/profile/personal-language-info.test.tsx, web/src/components/profile/personal-language-info.tsx, web/src/reducers/languages.test.ts, web/src/reducers/languages.ts, web/src/reducers/login.test.ts, web/src/reducers/login.ts, web/src/types.ts
* Every load of the stats component fetches the data from the backend
* Absolutely no caching on the client
* Initially also no caching on the backend, so up-to-date information is returned - if that turns out to be a general performance issue, we can introduce a backend cache
* Include language dropdown in stats page like we have for the review for example
* Some other small performance improvements
=> Statistics Improvements

server/lib/validation/index.js, server/lib/validation/languages/ca.js
Uses the gersam tokenizer for Catalan that counts a word with a dash as a single word.
=> feat: add sentence validator for catalan

package-lock.json, package.json, server/lib/validation/languages/eo.js, server/lib/validation/languages/tok.js
Wrote a new validation script for Toki Pona.
Changes compared to default:
- changed sentence limit from 14 words to 90 characters
- added rules to enforce Toki Pona's phonotactics, which should eliminate words and names with ambiguous or impossible pronunciations, and also catch a lot of typos
- added "capital letters at start of word only" rule, which can replace the default "no abbreviations" one
Also updated Esperanto's validation script with translations and minor improvements.
=> Create tok.js, update eo.js

server/lib/validation/languages/eo.js, server/lib/validation/languages/tok.js
Somehow `[BbCcDdFfGgHhQqRrVvXxYyZz\u00C0-\u02BF\u1E00-\u1EFF\uF1900-\uF19FF]` and `[qQwWxXyYÀ-ćĊ-ěĞ-ģĞ-ģĦ-ĳĶ-śŞ-ūŮ-\u02AF\u1E00-\u1EFFα-ωΑ-ΩЀ-ӿ]` match with all regular Latin letters as well, making the Sentence Collector reject all submissions.
Changed to `[BbCcDdFfGgHhQqRrVvXxYyZzÀ-ʯḀ-ỿ]` and `[qQwWxXyYÀ-ćĊ-ěĞ-ģĞ-ģĦ-ĳĶ-śŞ-ūŮ-ʯḀ-ỿα-ωΑ-ΩЀ-ӿ]`, which should work well. (At least they do in Notepad++, which I found has the same behavior.)
=> Fix to eo.js and tok.js validation scripts

web/src/reducers/index.ts
In order to simulate the issue reported by #609 I added some artificial delay in the `/review` endpoint of the server and while the web app was trying to fetch the sentences I just had to change pages or refresh your browser. This will make the app stuck in the loading state.
As mentioned by @MichaelKohler, the easy solution is to not persist the loading state `sentencesLoading`.
The key `isUploadingSentences` is also a loading state, but I was not able to simulate any issues like above because it goes to the catch and the state goes back to `false`. I also added it in the exception list just for consistency sake, but I can remove if you all think it is better since it is not causing real problems for now.
I didn't add any tests since it this case would be better tested by some type of …
=> fix: stop persisting loading state

server/lib/validation/index.js, server/lib/validation/languages/ko.js
This adds korean validation and cleanup.
- Korean script should only allow korean letters and some special characters `[.,?!]` (in my opinion).
- There are so many things to be not allowd, so I added the rule as whitelist rule.
- For responsive message I added some rules before it, which may be common mistakes.
- For sentence length calculation, I replaced it with character length.
- In my opinion, Tokenization is somewhat heavyweight for this task, especially in CJK (Chinese, Japanese, Korean).
- max length 50 is somewhat random, but the famous pengram "키스의 고유조건은 입술끼리 만나야 하고 특별한 기술은 필요치 않다" is 35 length so... It would be sufficient.
- About normalization
- Korean input system has (mainly) two kind of characters (in unicode space), which are interchangeable but have different unicode code …
=> add korean sentence validation & cleanup

server/lib/validation/index.js, server/lib/validation/languages/lo.js
Propose code for Lao language validator.
It's basic validator code.
=> Add validator for Lao (lo)

server/migrations/20230412115500-remove-fr-sentences-proper-nouns.js
This fixes the migration to remove FR sentences. FYI @moz-dfeller
=> fix: fix migration to have proper escape mechanism
